baseURL = "master-swept--laboring--shakiness-pgsdemo-com.preview.pagescdn.com"
languageCode = "en-us"
title = "Yext Sites Documentation"
theme = "themes/ace-documentation/"

[params]
    name = "gideon"
    site_logo = "/images/Yext_Seal_R_Web_White-300x300-a4acd96.png"


